# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a15123bf29e3f97480591911473d7747c4a0bb14d8dcfceee90051a26687aa03c23ce4022267e89ea1cc4acb009396c5150e5744bf8dd709ad735abbe2a1d51

test:
  secret_key_base: a2e9dbfd73367651b190a4ee0542495823ef01f0f46bec08fe03960d45d9540ce3dc07fa98b8f0bd8db491839f620db55eb93a10b22ce5cb38ee49efbc82f11e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
